defaults:
    - encoder: alexnet
    - learner: tactile_byol
    - dataset: tactile_tdex_dataset
    - optimizer: adam

seed: 42
device: cuda

learner_type: tactile_byol # Can be tactile_stacked_byol # tactile_stacked_byol tactile_linear_byol, bc, tactile_byol
self_supervised: true

# Hyperparameters to be used everywhere
batch_size: 1280
tactile_image_size: 224 # This could be changed for stacked or shared architectures
vision_image_size: 480
hidden_dim: 64
train_epochs: 500
save_frequency: 10
train_dset_split: 0.95

distributed: true
num_workers: 4
world_size: 1
num_gpus: 4

# Data path to be set
object: example_object
experiment: /root/to/save/the/models # Name of the experiment that the models are saved
data_dir: /data/root/${object}/all
checkpoint_dir: ??? # Will be set to hydra dir inside the code

# logger
logger: true # To init logger or not
log_frequency: 1

# hydra configuration - should be received separately
hydra:
    run:
        dir: /root/directory/of/the/project/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}
